#!/usr/bin/env bash
# Configure ufw so that it blocks all incoming traffic, except the following TCP ports
# 22, 443 and 80.

apt-get install ufw
ufw disable
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw

# Set the default policy
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp

ufw enable
