#!/usr/bin/env bash
# Install and run Apache on the holbertonschool/265-0 Docker container.

# Update the package list and install Apache.
apt-get update
apt-get install -y apache2

# Configure Apache to serve a page containing Hello Holberton.
echo "Hello Holberton" > /var/www/html/index.html

# Start Apache.
service apache2 start

docker run -p 8080:80 -d -it holbertonschool/265-0
